
CREATE DATABASE decoramor;

USE decoramor;

CREATE TABLE avaliacoes (
    id_avaliacao INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    comentario TEXT NOT NULL,
    nota INT NOT NULL,
    data_avaliacao DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO avaliacoes (nome, comentario, nota)
VALUES
('Maria Silva', 'Adorei o atendimento e a decoração!', 5),
('João Santos', 'Ambiente muito bonito e atendimento excelente.', 5),
('Ana Oliveira', 'Gostei muito do resultado.', 4);

SELECT * FROM avaliacoes;

SELECT
    nome,
    comentario,
    nota,
    data_avaliacao
FROM avaliacoes
ORDER BY data_avaliacao DESC;

SELECT
    ROUND(AVG(nota), 1) AS media_avaliacoes
FROM avaliacoes;




CREATE TABLE avaliacoes (
    id_avaliacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    comentario TEXT NOT NULL,
    nota INTEGER NOT NULL CHECK (nota >= 1 AND nota <= 5),
    data_avaliacao TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE avaliacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir visualizar avaliações"
ON avaliacoes
FOR SELECT
USING (true);

CREATE POLICY "Permitir inserir avaliações"
ON avaliacoes
FOR INSERT
WITH CHECK (true);
